apiVersion: storage.dell.com/v1
kind: CSIIsilon
metadata:
  name: isilon
  namespace: test-isilon
spec:
  driver:
    # Config version for CSI PowerScale v2.2.0 driver
    configVersion: v2.2.0
    replicas: 2
    dnsPolicy: ClusterFirstWithHostNet
    forceUpdate: false
    fsGroupPolicy: ReadWriteOnceWithFSType
    common:
      # Image for CSI PowerScale driver v2.2.0
      image: "dellemc/csi-isilon:v2.2.0"
      imagePullPolicy: IfNotPresent
      envs:
        # X_CSI_VERBOSE: Indicates what content of the OneFS REST API message should be logged in debug level logs
        # Allowed Values:
        #   0: log full content of the HTTP request and response
        #   1: log without the HTTP response body
        #   2: log only 1st line of the HTTP request and response
        # Default value: 0
        - name: X_CSI_VERBOSE
          value: "1"

        # X_CSI_ISI_PORT: Specify the HTTPs port number of the PowerScale OneFS API server
        # This value acts as a default value for endpointPort, if not specified for a cluster config in secret
        # Allowed value: valid port number
        # Default value: 8080	
        - name: X_CSI_ISI_PORT
          value: "8080"

        # X_CSI_ISI_PATH: The base path for the volumes to be created on PowerScale cluster.
        # This value acts as a default value for isiPath, if not specified for a cluster config in secret
        # Ensure that this path exists on PowerScale cluster.
        # Allowed values: unix absolute path
        # Default value: /ifs
        # Examples: /ifs/data/csi, /ifs/engineering
        - name: X_CSI_ISI_PATH
          value: "/ifs/data/csi"

        # X_CSI_ISI_NO_PROBE_ON_START: Indicates whether the controller/node should probe all the PowerScale clusters during driver initialization
        # Allowed values:
        #   true : do not probe all PowerScale clusters during driver initialization	
        #   false: probe all PowerScale clusters during driver initialization
        # Default value: false
        - name: X_CSI_ISI_NO_PROBE_ON_START
          value: "false"

        # X_CSI_ISI_AUTOPROBE: automatically probe the PowerScale cluster if not done already during CSI calls.
        # Allowed values:
        #   true : enable auto probe.
        #   false: disable auto probe.
        # Default value: false
        - name: X_CSI_ISI_AUTOPROBE
          value: "true"

        # X_CSI_ISI_SKIP_CERTIFICATE_VALIDATION: Specify whether the PowerScale OneFS API server's certificate chain and host name should be verified.
        # Formerly this attribute was named as "X_CSI_ISI_INSECURE"
        # This value acts as a default value for skipCertificateValidation, if not specified for a cluster config in secret
        # Allowed values:
        #   true: skip OneFS API server's certificate verification
        #   false: verify OneFS API server's certificates
        # Default value: false	
        - name: X_CSI_ISI_SKIP_CERTIFICATE_VALIDATION
          value: "true"

        # X_CSI_ISI_AUTH_TYPE: Indicates whether the authentication will be session-based or basic.
        # Allowed values:
        #   0: enables basic Authentication
        #   1: enables session-based Authentication
        # Default value: 0
        - name: X_CSI_ISI_AUTH_TYPE
          value: "0"

        # X_CSI_CUSTOM_TOPOLOGY_ENABLED: Specify if custom topology label <provisionerName>.dellemc.com/<powerscalefqdnorip>:<provisionerName>
        # has to be used for making connection to backend PowerScale Array.
        # If X_CSI_CUSTOM_TOPOLOGY_ENABLED is set to true, then do not specify allowedTopologies in storage class.
        # Allowed values:
        #   true : enable custom topology
        #   false: disable custom topology
        # Default value: false
        - name: X_CSI_CUSTOM_TOPOLOGY_ENABLED
          value: "false"

    controller:
      envs:
      # X_CSI_ISI_QUOTA_ENABLED: Indicates whether the provisioner should attempt to set (later unset) quota
      # on a newly provisioned volume.
      # This requires SmartQuotas to be enabled on PowerScale cluster.
      # Allowed values:
      #   true: set quota for volume
      #   false: do not set quota for volume
      - name: X_CSI_ISI_QUOTA_ENABLED
        value: "true"

      # X_CSI_ISI_ACCESS_ZONE: The name of the access zone a volume can be created in.
      # If storageclass is missing with AccessZone parameter, then value of X_CSI_ISI_ACCESS_ZONE is used for the same.
      # Default value: System
      # Examples: System, zone1
      - name: X_CSI_ISI_ACCESS_ZONE
        value: "System"

      # X_CSI_ISI_VOLUME_PATH_PERMISSIONS: The permissions for isi volume directory path
      # This value acts as a default value for isiVolumePathPermissions, if not specified for a cluster config in secret
      # Allowed values: valid octal mode number
      # Default value: "0777"
      # Examples: "0777", "777", "0755"
      - name: X_CSI_ISI_VOLUME_PATH_PERMISSIONS
        value: "0777"

      # nodeSelector: Define node selection constraints for pods of controller deployment.
      # For the pod to be eligible to run on a node, the node must have each
      # of the indicated key-value pairs as labels.
      # Leave as blank to consider all nodes
      # Allowed values: map of key-value pairs
      # Default value: None
      # Examples:
      #   node-role.kubernetes.io/master: ""
      nodeSelector:
      #  node-role.kubernetes.io/master: ""

      # tolerations: Define tolerations for the controller deployment, if required.
      # Default value: None
      tolerations:
      #  - key: "node-role.kubernetes.io/master"
      #    operator: "Equal"
      #    value: "true"
      #    effect: "NoSchedule"

    node:
      envs:
      # X_CSI_MAX_VOLUMES_PER_NODE: Specify default value for maximum number of volumes that controller can publish to the node.
      # If value is zero CO SHALL decide how many volumes of this type can be published by the controller to the node.
      # This limit is applicable to all the nodes in the cluster for which node label 'max-isilon-volumes-per-node' is not set.
      # Allowed values: n, where n >= 0
      # Default value: 0
      - name: X_CSI_MAX_VOLUMES_PER_NODE
        value: "0"

      # X_CSI_ALLOWED_NETWORKS: Custom networks for PowerScale export
      # Specify list of networks which can be used for NFS I/O traffic; CIDR format should be used.
      # Allowed values: list of one or more networks
      # Default value: None
      # Provide them in the following format: "[net1, net2]"
      # CIDR format should be used
      # eg: "[192.168.1.0/24, 192.168.100.0/22]"
      - name: X_CSI_ALLOWED_NETWORKS
        value: ""

      # nodeSelector: Define node selection constraints for pods of node daemonset
      # For the pod to be eligible to run on a node, the node must have each
      # of the indicated key-value pairs as labels.
      # Leave as blank to consider all nodes
      # Allowed values: map of key-value pairs
      # Default value: None
      # Examples:
      #   node-role.kubernetes.io/master: ""
      nodeSelector:
      #  node-role.kubernetes.io/master: ""

      # tolerations: Define tolerations for the node daemonset, if required.
      # Default value: None
      tolerations:
      #  - key: "node.kubernetes.io/memory-pressure"
      #    operator: "Exists"
      #    effect: "NoExecute"
      #  - key: "node.kubernetes.io/disk-pressure"
      #    operator: "Exists"
      #    effect: "NoExecute"
      #  - key: "node.kubernetes.io/network-unavailable"
      #    operator: "Exists"
      #    effect: "NoExecute"

    sideCars:
      - name: provisioner
        args: ["--volume-name-prefix=csipscale"]
